name: Node.js CI/CD

on:
  push:
    branches: [ "Danish" ] #provide your branch name
  pull_request:
    branches: [ "Danish" ] #provide your branch name

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.14.0] #Give the installed nodejs version of EC2

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
